###############
# VUE BUILDER #
###############
FROM node:15-alpine3.10 as build-vue

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./client/package*.json ./
RUN npm install

COPY ./client .
RUN npm run build

##############
# PRODUCTION #
##############
FROM nginx:1.25.3-alpine

COPY --from=build-vue /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d